# Source: krawl-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krawl
  namespace: krawl-system
  labels:
    app.kubernetes.io/name: krawl
    app.kubernetes.io/instance: krawl
    app.kubernetes.io/version: "2.1.0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: krawl
      app.kubernetes.io/instance: krawl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: krawl
        app.kubernetes.io/instance: krawl
    spec:
      containers:
      - name: krawl
        image: "ghcr.io/blessedrebus/krawl:1.2.0"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        env:
        - name: CONFIG_LOCATION
          value: "config.yaml"
        # Uncomment to use dashboard password from secret
        # - name: KRAWL_DASHBOARD_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: krawl-dashboard
        #       key: dashboard-password
        - name: KRAWL_MODE
          value: "scalable"
        - name: KRAWL_POSTGRES_HOST
          value: "postgres"
        - name: KRAWL_POSTGRES_PORT
          value: "5432"
        - name: KRAWL_POSTGRES_USER
          value: "krawl"
        - name: KRAWL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: krawl-postgres
              key: postgres-password
        - name: KRAWL_POSTGRES_DATABASE
          value: "krawl"
        - name: KRAWL_REDIS_HOST
          value: "redis"
        - name: KRAWL_REDIS_PORT
          value: "6379"
        - name: KRAWL_REDIS_DB
          value: "0"
        - name: KRAWL_REDIS_CACHE_TTL
          value: "600"
        - name: KRAWL_REDIS_HOT_TTL
          value: "30"
        - name: KRAWL_REDIS_TABLE_TTL
          value: "120"
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
          readOnly: true
        - name: wordlists
          mountPath: /app/wordlists.json
          subPath: wordlists.json
          readOnly: true
        resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
      volumes:
      - name: config
        configMap:
          name: krawl-config
      - name: wordlists
        configMap:
          name: krawl-wordlists
