# Source: krawl-chart/templates/network-policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: krawl
  namespace: krawl-system
  labels:
    app.kubernetes.io/name: krawl
    app.kubernetes.io/instance: krawl
    app.kubernetes.io/version: "2.1.0"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: krawl
      app.kubernetes.io/instance: krawl
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector: {}
      - namespaceSelector: {}
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
      - port: 5000
        protocol: TCP
  egress:
    - ports:
      - protocol: TCP
      - protocol: UDP
      to:
      - namespaceSelector: {}
      - ipBlock:
          cidr: 0.0.0.0/0
