# Source: krawl-chart/templates/postgres.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: krawl-system
  labels:
    app.kubernetes.io/name: krawl
    app.kubernetes.io/instance: krawl
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: krawl-postgres
    app.kubernetes.io/instance: krawl
