# Source: krawl-chart/templates/postgres.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: krawl-postgres
  namespace: krawl-system
  labels:
    app.kubernetes.io/name: krawl
    app.kubernetes.io/instance: krawl
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
