# Source: krawl-chart/templates/redis.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: krawl-system
  labels:
    app.kubernetes.io/name: krawl
    app.kubernetes.io/instance: krawl
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: krawl-redis
    app.kubernetes.io/instance: krawl
