{{- if or (eq .Values.mode "scalable") .Values.migration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krawl.fullname" . }}-postgres
  labels:
    {{- include "krawl.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
---
{{- if .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krawl.fullname" . }}-redis
  labels:
    {{- include "krawl.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password | quote }}
{{- end }}
{{- end }}
