{{- if .Values.config.ai.api_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krawl.fullname" . }}-ai
  labels:
    {{- include "krawl.labels" . | nindent 4 }}
type: Opaque
stringData:
  ai-api-key: {{ .Values.config.ai.api_key | quote }}
{{- end }}
