{{- if .Values.dashboardPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krawl.fullname" . }}-dashboard
  labels:
    {{- include "krawl.labels" . | nindent 4 }}
type: Opaque
stringData:
  dashboard-password: {{ .Values.dashboardPassword | quote }}
{{- end }}
